config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :likes

      resources :messages

      resources :photos

      resources :stays

      resources :rooms

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "rooms#index"
  resources :likes
  resources :messages
  resources :photos
  resources :stays
  resources :rooms
  get "liked_rooms" => "rooms#likes"
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  include JwtToken
  # Direct associations

  has_many   :likes,
             dependent: :destroy

  has_many   :recieved_messages,
             class_name: "Message",
             foreign_key: "recipient_id",
             dependent: :destroy

  has_many   :sent_messages,
             class_name: "Message",
             foreign_key: "sender_id",
             dependent: :destroy

  has_many   :stays,
             foreign_key: "guest_id",
             dependent: :destroy

  has_many   :rooms,
             foreign_key: "host_id",
             dependent: :destroy

  # Indirect associations

  has_many   :senders,
             through: :recieved_messages,
             source: :sender

  has_many   :recipients,
             through: :sent_messages,
             source: :recipient

  has_many   :stayed_rooms,
             through: :stays,
             source: :room

  has_many   :liked_rooms,
             through: :likes,
             source: :room

has_many(:recipients, through: :sent_messages, source: :recipient)
  has_many(:senders, through: :recieved_messages, source: :sender)
  # Validations

  validates :name, presence: true

  # Scopes

  def to_s
    name
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::GraphitiController
  def index
    users = UserResource.all(params)
    respond_with(users)
  end

  def show
    user = UserResource.find(params)
    respond_with(user)
  end

  def create
    user = UserResource.build(params)

    if user.save
      render jsonapi: user, status: :created
    else
      render jsonapi_errors: user
    end
  end

  def update
    user = UserResource.find(params)

    if user.update_attributes
      render jsonapi: user
    else
      render jsonapi_errors: user
    end
  end

  def destroy
    user = UserResource.find(params)

    if user.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: user
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @users = User.page(params[:page]).per(10)
  end

  def show
    @like = Like.new
    @message = Message.new
    @stay = Stay.new
    @room = Room.new
  end

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: "User was successfully created."
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "User was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: "User was successfully destroyed."
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name)
  end
end

app/views/users/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    User #<%= user.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Name</dt>
      <dd><%= user.name %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back user, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_user_url(user), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to user, method: :delete, data: { confirm: "Do you really want to delete this user?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(user.updated_at) %> ago
  </div>
</div>

app/views/users/_user_interactions_a.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Interactions A

    <a data-toggle="collapse" href="#user_interactions_a_new_form">
      Add interaction
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @user.interactions_a.each do |interaction| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to interaction, interaction %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="user_interactions_a_new_form">
        <%= render partial: "users/user_interactions_a_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/users/_user_interactions_a_new_form.html.erb
<%= form_with(model: @interaction, local: true) do |f| %>

  <%= f.hidden_field :sender_id, value: current_user.id %>
  <%= f.hidden_field :recipient_id, value: @room.host.id %>
  <%= f.hidden_field :room_id, value: @room.id %>

  <div class="form-group">
    <%= f.label :body, class: "sr-only" %>
    <%= f.text_area :body, rows: "3", class: "form-control" %>
  </div>

  <%= f.submit "Send message", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/users/_user_interactions_b_new_form.html.erb
<%= form_with(model: @interaction, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :sender_id %>

    <%= f.text_field :sender_id, class: "form-control" %>
  </div>

  <%= f.hidden_field :recipient_id, value: @user.id %>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, rows: "3", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :room_id %>

    <%= f.collection_select :room_id, Room.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <%= f.submit "Create interaction", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/users/_user_liked_rooms.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Liked Rooms
  </div>

  <ul class="list-group list-group-flush">
    <% @user.liked_rooms.each do |room| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <a href="/rooms/<%= room.id %>">
          <%= room %>
        </a>

      </li>
    <% end %>

  </ul>
</div>

app/views/users/_user_likes.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Likes

    <a data-toggle="collapse" href="#user_likes_new_form">
      Add like
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @user.likes.each do |like| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to like, like %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="user_likes_new_form">
        <%= render partial: "users/user_likes_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/users/_user_lines.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Lines

    <a data-toggle="collapse" href="#user_lines_new_form">
      Add line
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @user.lines.each do |line| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to line, line %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="user_lines_new_form">
        <%= render partial: "users/user_lines_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/users/_user_lines_new_form.html.erb
<%= form_with(model: @line, local: true) do |f| %>

  <%= f.hidden_field :user_id, value: @user.id %>

  <div class="form-group">
    <%= f.label :location_id %>

    <%= f.collection_select :location_id, Room.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <%= f.submit "Create line", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/users/_user_recieved_messages.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Recieved Messages

    <a data-toggle="collapse" href="#user_recieved_messages_new_form">
      Add message
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @user.recieved_messages.each do |message| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to message, message %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="user_recieved_messages_new_form">
        <%= render partial: "users/user_recieved_messages_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/users/_user_recieved_messages_new_form.html.erb
<%= form_with(model: @message, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :sender_id %>

    <%= f.text_field :sender_id, class: "form-control" %>
  </div>

  <%= f.hidden_field :recipient_id, value: @user.id %>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, rows: "3", class: "form-control" %>
  </div>

  <%= f.submit "Create message", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/users/_user_rooms.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Rooms

    <a data-toggle="collapse" href="#user_rooms_new_form">
      Add room
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @user.rooms.each do |room| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to room, room %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="user_rooms_new_form">
        <%= render partial: "users/user_rooms_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/users/_user_sent_messages.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Sent Messages

    <a data-toggle="collapse" href="#user_sent_messages_new_form">
      Add message
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @user.sent_messages.each do |message| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to message, message %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="user_sent_messages_new_form">
        <%= render partial: "users/user_sent_messages_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/users/_user_user_user_rooms.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Past trips
  </div>

  <ul class="list-group list-group-flush">
    <% @user.user_user_rooms.each do |room| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <a href="/rooms/<%= room.id %>">
          <%= room %>
        </a>

      </li>
    <% end %>

  </ul>
</div>

app/views/users/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Users

      <%= link_to new_user_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>






<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Users

        <%= link_to new_user_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @users, partial: "list_item", as: :user %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @users, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>