config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :likes

      resources :messages

      resources :photos

      resources :stays

      resources :rooms

      resources :users
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "rooms#index"
  resources :likes
  resources :messages
  resources :photos
  resources :stays
  resources :rooms
  get "liked_rooms" => "rooms#likes"
  devise_for :users
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  # Direct associations

  belongs_to :room

  belongs_to :guest,
             class_name: "User"

  # Indirect associations

  # Validations

  validates :check_in, presence: true

  validates :check_out, presence: true

  # Scopes

  def to_s
    "Trip at #{room.name} from #{check_in.strftime("%b %d, %Y")} to #{check_out.strftime("%b %d, %Y")}"
  end
end

app/controllers/api/v1/user_rooms_controller.rb
class Api::V1::UserRoomsController < Api::V1::GraphitiController
  def index
    user_rooms = UserRoomResource.all(params)
    respond_with(user_rooms)
  end

  def show
    user_room = UserRoomResource.find(params)
    respond_with(user_room)
  end

  def create
    user_room = UserRoomResource.build(params)

    if user_room.save
      render jsonapi: user_room, status: :created
    else
      render jsonapi_errors: user_room
    end
  end

  def update
    user_room = UserRoomResource.find(params)

    if user_room.update_attributes
      render jsonapi: user_room
    else
      render jsonapi_errors: user_room
    end
  end

  def destroy
    user_room = UserRoomResource.find(params)

    if user_room.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: user_room
    end
  end
end

app/controllers/user_rooms_controller.rb
class UserRoomsController < ApplicationController
  before_action :set_user_room, only: %i[show edit update destroy]

  def index
    @q = UserRoom.ransack(params[:q])
    @user_rooms = @q.result(distinct: true).includes(:guest,
                                                     :room).page(params[:page]).per(10)
  end

  def show; end

  def new
    @user_room = UserRoom.new
  end

  def edit; end

  def create
    @user_room = UserRoom.new(user_room_params)

    if @user_room.save
      message = "Your trip is pending approval."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @user_room, notice: message
      end
    else
      render :new
    end
  end
  
  def update
    if @user_room.update(user_room_params)
      redirect_back fallback_location: request.referer, notice: "User room was successfully updated."
      # redirect_to @user_room, notice: "User room was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @user_room.destroy
    message = "Trip was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to user_rooms_url, notice: message
    end
  end

  private

  def set_user_room
    @user_room = UserRoom.find(params[:id])
  end

  def user_room_params
    params.require(:user_room).permit(:guest_id, :room_id, :check_in,
                                      :check_out, :approved)
  end
end

app/views/user_rooms/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    User Room #<%= user_room.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Guest</dt>
      <dd>
        <% if @user_room.guest.present? %>
          <%= link_to user_room.guest, user_room.guest %>
        <% end %>
      </dd>

      <dt>Room</dt>
      <dd>
        <% if @user_room.room.present? %>
          <%= link_to user_room.room, user_room.room %>
        <% end %>
      </dd>

      <dt>Check in</dt>
      <dd><%= user_room.check_in %></dd>

      <dt>Check out</dt>
      <dd><%= user_room.check_out %></dd>

      <dt>Approved</dt>
      <dd><%= user_room.approved %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back user_room, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_user_room_url(user_room), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to user_room, method: :delete, data: { confirm: "Do you really want to delete this user_room?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(user_room.updated_at) %> ago
  </div>
</div>

app/views/user_rooms/_form.html.erb
<% was_validated = user_room.errors.any? %>

<%= form_with(model: user_room, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% guest_class = "form-control" %>
    <% guest_was_invalid = user_room.errors.include?(:guest) %>

    <% if was_validated %>
      <% if guest_was_invalid %>
        <% guest_class << " is-invalid" %>
      <% else %>
        <% guest_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :guest_id %>
    <%= f.collection_select :guest_id, User.all, :id, :to_s, {}, class: "form-control" %>
    <% if guest_was_invalid %>
      <% user_room.errors.full_messages_for(:guest).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% room_class = "form-control" %>
    <% room_was_invalid = user_room.errors.include?(:room) %>

    <% if was_validated %>
      <% if room_was_invalid %>
        <% room_class << " is-invalid" %>
      <% else %>
        <% room_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :room_id %>
    <%= f.collection_select :room_id, Room.all, :id, :to_s, {}, class: "form-control" %>
    <% if room_was_invalid %>
      <% user_room.errors.full_messages_for(:room).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% check_in_class = "form-control" %>
    <% check_in_was_invalid = user_room.errors.include?(:check_in) %>

    <% if was_validated %>
      <% if check_in_was_invalid %>
        <% check_in_class << " is-invalid" %>
      <% else %>
        <% check_in_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :check_in %>
    <%= f.date_select :check_in, class: check_in_class, placeholder: "Enter check in" %>
    <% if check_in_was_invalid %>
      <% user_room.errors.full_messages_for(:check_in).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% check_out_class = "form-control" %>
    <% check_out_was_invalid = user_room.errors.include?(:check_out) %>

    <% if was_validated %>
      <% if check_out_was_invalid %>
        <% check_out_class << " is-invalid" %>
      <% else %>
        <% check_out_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :check_out %>
    <%= f.date_select :check_out, class: check_out_class, placeholder: "Enter check out" %>
    <% if check_out_was_invalid %>
      <% user_room.errors.full_messages_for(:check_out).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-check">
    <% approved_class = "form-check-input" %>
    <% approved_was_invalid = user_room.errors.include?(:approved) %>

    <% if was_validated %>
      <% if approved_was_invalid %>
        <% approved_class << " is-invalid" %>
      <% else %>
        <% approved_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :approved, class: "form-check-label" do %>
      <%= f.check_box :approved, class: approved_class %> Approved
    <% end %>
    <% if approved_was_invalid %>
      <% user_room.errors.full_messages_for(:approved).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/user_rooms/_list_item.html.erb
<%= link_to user_room.room, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div class="row">
    <div class="col-4">
      <%= cl_image_tag user_room.room.photos.first&.url, class: "img-fluid" %>
    </div>
    <div class="col-8">
      <%= user_room %>
    </div>
  </div>
<% end %>

app/views/user_rooms/_user_rooms_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "user_rooms_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :check_in, "Check in" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='check_ingteqPicker' data-target-input="nearest">
          <%= f.text_field :check_in_gteq, :class => "form-control datetimepicker-input", :placeholder => "Check in greater than or equal to", :data => {:target => '#check_ingteqPicker'} %>
          <div class="input-group-append" data-target='#check_ingteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='check_inlteqPicker' data-target-input="nearest">
          <%= f.text_field :check_in_lteq, :class => "form-control datetimepicker-input", :placeholder => "Check in less than or equal to", :data => {:target => '#check_inlteqPicker'} %>
          <div class="input-group-append" data-target='#check_inlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#check_ingteqPicker').datetimepicker({
              format: 'MM/DD/YYYY'
          });
          $('#check_inlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'MM/DD/YYYY'
          });
          $('#check_ingteqPicker').on("dp.change", function (e) {
              $('#check_inlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#check_inlteqPicker').on("dp.change", function (e) {
              $('#check_ingteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>

  <div class="form-group">
    <%= f.label :approved_eq, "Approved" %>
    <div>
      <label class="radio-inline">
        <%= f.radio_button :approved_eq, "1", checked: ((params[:q] && params[:q][:approved_eq]) == "1" ? "checked" : "") %> Yes
      </label>
      <label class="radio-inline">
        <%= f.radio_button :approved_eq, "0", checked: ((params[:q] && params[:q][:approved_eq]) == "0" ? "checked" : "")%> No
      </label>
      <label class="radio-inline">
        <%= f.radio_button :approved_eq, ""%> Either
      </label>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :check_out, "Check out" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='check_outgteqPicker' data-target-input="nearest">
          <%= f.text_field :check_out_gteq, :class => "form-control datetimepicker-input", :placeholder => "Check out greater than or equal to", :data => {:target => '#check_outgteqPicker'} %>
          <div class="input-group-append" data-target='#check_outgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='check_outlteqPicker' data-target-input="nearest">
          <%= f.text_field :check_out_lteq, :class => "form-control datetimepicker-input", :placeholder => "Check out less than or equal to", :data => {:target => '#check_outlteqPicker'} %>
          <div class="input-group-append" data-target='#check_outlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#check_outgteqPicker').datetimepicker({
              format: 'MM/DD/YYYY'
          });
          $('#check_outlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'MM/DD/YYYY'
          });
          $('#check_outgteqPicker').on("dp.change", function (e) {
              $('#check_outlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#check_outlteqPicker').on("dp.change", function (e) {
              $('#check_outgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :guest_name_cont, "Guest name contains" %>
    <%= f.text_field :guest_name_cont, :class => "form-control", :placeholder => "Guest name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :room_name_cont, "Room name contains" %>
    <%= f.text_field :room_name_cont, :class => "form-control", :placeholder => "Room name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/user_rooms" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#user_rooms_filters">
  Show filters
</a>

app/views/user_rooms/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit User Room #<%= @user_room.id %>
      </h2>

      <div class="card-body">
        <%= render "form", user_room: @user_room %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/user_rooms/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Stays
    </h1>
  </div>
</div>


<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Past trips
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @user_rooms.where(check_out: ..Date.current), partial: "list_item", as: :user_room %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @user_rooms.where(check_out: ..Date.current), theme: 'twitter-bootstrap-4' %>
      </div>
    </div>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Upcoming trips
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @user_rooms.where(check_out: Date.current..), partial: "list_item", as: :user_room %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @user_rooms.where(check_out: Date.current..), theme: 'twitter-bootstrap-4' %>
      </div>
    </div>
  </div>
</div>

app/views/user_rooms/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New User Room
      </h2>

      <div class="card-body">
        <%= render "form", user_room: @user_room %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/user_rooms/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @user_room, partial: "card", as: :user_room %>
  </div>
</div>